% -------------------------------------------------------------------
%  Generated by MATLAB on 12-Mar-2024 11:47:51
%  MATLAB version: 23.2.0.2409890 (R2023b) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('livestream.mat');

data = saveVarsMat.data; % <1x1 NatNetML.FrameOfMocapData> unsupported class

clear saveVarsMat;
